### ISSUE TITLE
mount command is missing

### ISSUE THREAD

**Issue by dsommers** [flathub/org.thonny.Thonny#153]
When running a fresh install of this flatpak and trying to choose a Pimoroni device, I get this splat in an error window:

```
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/app/lib/python3.10/site-packages/thonny/workbench.py", line 865, in _post_backend_menu
    if uf2_device_is_present_in_bootloader_mode():
  File "/app/lib/python3.10/site-packages/thonny/plugins/micropython/uf2dialog.py", line 602, in uf2_device_is_present_in_bootloader_mode
    for vol in list_volumes(skip_letters=["A"]):
  File "/app/lib/python3.10/site-packages/thonny/misc_utils.py", line 101, in list_volumes
    mount_output = subprocess.check_output("mount").splitlines()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mount'
```

It seems the `mount` command is lacking.  I've tried to give it full filesystem access via Flatseal, granting "All system files", "All system libraries, executables and static data" and "All system configurations" and still having the same issue after restarting the Thonny flatpak.

**Comment by dsommers** [comment]
Btw, latest pip install version works out-of-the-box on the same host.

**Comment by jwillikers** [comment]
@dsommers Thanks for submitting this issue. I have several Pimoroni devices, and was able to reproduce by clicking `Install or update MicroPython` in the `Interpreter` tab in `Thonny options`. I've never tried this before but has been on my list to attempt. I think this will be a problem for any MicroPython device at the moment. It's due to the fact that `mount` does not exist inside the Flatpak runtimes due to restrictions around the sandbox.

We'll need to rewrite the way Thonny mounts devices on Linux to prefer the UDisks2 DBUS API over using the `mount` command directly. This works better for users since it allows mounting without requiring `root` priviliges. It looks like the Calibre Flatpak figured out how to do accomplish this.  For reference by my future self, this is discussed in issue flathub/com.calibre_ebook.calibre#9. I should be able to work with the Thonny project upstream to make this change.

For now, you'll want to manually install firmware by holding the `boot` button while either plugging in the device or clicking the `reset` button while the device is plugged in. Using your system's file manager, you should be able to drag-n-drop the desired UF2 file to the `RPI-RP2` drive that appears. Once the drive is finished writing, it will reboot automatically. You should still be able to connect to it via Thonny by selecting `MicroPython (Raspberry Pi Pico)` as the interpreter and selecting `Ok`.

**Comment by dsommers** [comment]
Let me know when you have something ready for testing, including out-of-tree (as long as I have needed instructions).

**Comment by jwillikers** [comment]
Related issues: thonny/thonny#2650 and thonny/thonny#2426.

**Comment by jwillikers** [comment]
I propose we introduce a dependency on [python-dbus-next](https://github.com/altdesktop/python-dbus-next) on Linux in order to mount filesystems with [UDisks2](https://github.com/storaged-project/udisks) via its [DBUS API](http://storaged.org/doc/udisks2-api/latest/ref-dbus.html). I imagine I'll be able to get to this before too terribly long.
