### ISSUE TITLE
Thonny with pip does not work on steam deck

### ISSUE THREAD

**Issue by Davidm16** [flathub/org.thonny.Thonny#259]
I installed thonny flatpak beta in steam os but it does not allow the installation of modules by pip

**Comment by jwillikers** [comment]
@Davidm16 Thank you for reporting. Could try switching to the stable channel? The beta only gets updated when Thonny has release candidates out, so it hasn't been updated in a while.

**Comment by jwillikers** [comment]
I would recommend using a virtual environment through interpreter settings, but I don't that is currently working in the Flatpak, as I attempted it and hit an error. I'll need to open up a proper issue upstream when I find the time for the virtual environment issue. For just using pip out-of-the-box, I need to try and figure out why I originally disallowed that when the Flatpak was originally made, that why I can determine if it's possible to enable support for it somehow.

**Comment by jwillikers** [comment]
Okay, so I think it started coming back to me. From what I remember, I had two options to accomplish this. I could map the user's local Python directory, i.e. the relevant subdirectories under `~/.local`, inside the Flatpak or I could persist those directories inside the Flatpak. There's two issues with the first method. There's a bit of a security risk if I make a user's Python directory in `~/.local` accessible to the Flatpak and Flatpaks are supposed to be separate from local installations of the same application. Plugins and what not in the local user's Python installation could effect the Flatpak as well as alternative installations such as ones installed with `pip`. The second option is what I think I attempted, but for some reason I had trouble getting the directory to properly persist. What would happen is that packages would be installed to `~/.local` inside the Flatpak's sandbox, but then they would disappear anytime the Flatpak was updated. I think there were some difficult to overcome limitations around this which is why we ended up disabling it in the app. I'll probably still poke at this to see if I can get it working. 

All that being said, it should definitely still be possible to use `venv`'s, but it appears there's now a bug effecting that functionality. I'll try to get a proper bug report filed tomorrow and start investigating that. Hopefully it won't take us too long to get that patched up and working again.

**Comment by jwillikers** [comment]
And, here's the error attempting to install a package in a `venv`:

```
PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_active_distributions' (ModuleNotFoundError: No module named 'pkg_resources').
See Thonny's backend.log for more info.

Process ended with exit code 1.
```

I also get an error when creating the `venv`, though it still seems to get created.

**Comment by jwillikers** [comment]
@Davidm16 Hmm, I think installing with `pip` is actually possible using `Manage packages`. Is the right interpreter selected and did you hit `Open system shell...`? That one isn't possible in the Flatpak. The `pip` install should work and correctly persist packages for the Flatpak.

**Comment by Davidm16** [comment]
I need the shell to install opencv on Steam OS, I can’t do it from the Manage packages

**Comment by jwillikers** [comment]
> I need the shell to install opencv on Steam OS, I can’t do it from the Manage packages

@Davidm16 How are you installing it? I can install via `Manage packages` using the `opencv-python` package.

**Comment by Davidm16** [comment]
Opencv 4.5.1.48 displays this: Failed building wheel for numpy" ..... platform machine != "aarch64" don't match your enviroment. Internal error?

**Comment by jwillikers** [comment]
> Opencv 4.5.1.48 displays this: Failed building wheel for numpy" ..... platform machine != "aarch64" don't match your enviroment. Internal error?

I don't think that's the actual error. If I install that exact version it hits a bunch of compiler errors building numpy. There is this message: `RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.11.`, which indicates that Python 3.11 may be too new for that version of `numpy` for OpenCV 4.5.1.48. It's probably necessary to use a newer version at that point. You may be able to install an older version of Python, create a `venv`, and then open that virtual environment with Thonny.

**Comment by Davidm16** [comment]
In conclusion it is not possible to open the system shell to install by but it is possible to install libraries using Manage packages which is the same. Thank you! this issue is resolved
